"""
main.py
-------
FastAPI application entry point (blueprint Section 9). Wires together every
route module and initializes the database on startup.

Run locally with:
    uvicorn api.main:app --reload --port 8000

Then visit http://localhost:8000/docs for the interactive API docs
(auto-generated by FastAPI from the Pydantic schemas in api/schemas/).
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from src.database.session import init_db
from api.routes import analyst, analytics, events, forecast, graph, health, threats, upload, url_scan, users


@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    yield


app = FastAPI(
    title="ThreatLens AI API",
    description="AI-powered cyber threat intelligence & attack prediction platform.",
    version="1.0.0",
    lifespan=lifespan,
)

# Permissive CORS so the standalone frontend (served separately, e.g. via
# Vercel or a local file server) can call this API during development.
# Tighten `allow_origins` to your real frontend domain before production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health.router)
app.include_router(events.router)
app.include_router(threats.router)
app.include_router(users.router)
app.include_router(forecast.router)
app.include_router(graph.router)
app.include_router(analyst.router)
app.include_router(analytics.router)
app.include_router(upload.router)
app.include_router(url_scan.router)


@app.get("/")
def root():
    return {
        "name": "ThreatLens AI API",
        "status": "running",
        "docs": "/docs",
    }
